language: php

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

sudo: false

branches:
    - master
    - 1.0

git:
    depth: 1

install:
    - composer install --prefer-dist

cache:
    - apt
    - $HOME/.composer/cache

script: vendor/bin/phpunit
