language: php

php:
    - '5.6'
    - '7.0'
    - hhvm
    - nightly

sudo: false

git:
    depth: 1

install:
    - composer install --prefer-dist

cache:
    - $HOME/.composer/cache

script: vendor/bin/phpunit
